name: System Info

on:
  push:
    branches:
      - main  

jobs:
  system_info:
    runs-on: ubuntu-latest
    steps:
    - name: Get system info
      run: |
        echo "System Information:"
        
        echo "Processors: $(nproc) cores"
        
        echo "Memory: $(free -h | grep Mem | awk '{print $2}')"
        
        echo "Storage: $(df -h / | tail -1 | awk '{print $2}')"
        
        echo "Architecture: $(uname -m)"
